### ISSUE TITLE
Fail to start normally in local env

### ISSUE THREAD

**Issue by ulivz** [marko-js/markojs.com#25]
Hey, I want to see the docs in my local env, I just handle by following the README.md,
```
npm i && npm start
```

My Node Version is `4.7.0`;
My OS is `OSX 10.12.3`;

And It shows error as follows:

```
(function (exports, require, module, __filename, __dirname) { const {OnigScanner, OnigString} = require('../build/Release/onig_scanner.node')
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/haolchen/Documents/Coding/My/Marko/markojs.com/node_modules/highlights/node_modules/first-mate/lib/grammar.js:10:16)
    at Object.<anonymous> (/Users/haolchen/Documents/Coding/My/Marko/markojs.com/node_modules/highlights/node_modules/first-mate/lib/grammar.js:380:4)
    at Module._compile (module.js:409:26)
```

**Comment by austinkelleher** [comment]
Hey, this is the Marko v3 website, and we aren't actively maintaining this repo anymore since we've moved to Marko v4. We should probably get this repo back in working order. 

The real repo that you should be interested in looking at is https://github.com/marko-js/markojs-website. Make sure you're using at least Node v6 for the markojs-website repo.

Additionally, the Marko docs are not stored in the markojs-website repo, we store them in the Marko repo and they get pulled into the website: https://github.com/marko-js/marko/tree/master/docs

I'm going to leave this issue open to fix the broken code here.

**Comment by ulivz** [comment]
@austinkelleher Thanks
